import { StyleSheet } from "react-native";

export default StyleSheet.create({
  contiainer: {
    flex: 1,
    paddingTop: 5,
    paddingRight: 15,
    paddingLeft: 15,
    paddingBottom: 15,
    backgroundColor: "white",
    flexGrow: 1,
  },
  img_bg: {
    shadowColor: "black",
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.37,
    shadowRadius: 7.49,
    elevation: 12,
  },
  back_icon: {
    backgroundColor: "white",
    width: 50,
    height: 40,
    display: "flex",
    justifyContent: "center",
    alignContent: "center",
    borderRadius: 10,
    position: "absolute",
    zIndex: 2,
    left: 10,
    top: 20,
  },
  heart_icon: {
    backgroundColor: "white",
    width: 50,
    height: 40,
    display: "flex",
    justifyContent: "center",
    alignContent: "center",
    borderRadius: 10,
    position: "absolute",
    zIndex: 2,
    right: 10,
    top: 20,
  },
  type: {
    backgroundColor: "black",
    width: 150,
    height: 50,
    display: "flex",
    justifyContent: "center",
    alignContent: "center",
    borderRadius: 10,
    position: "absolute",
    zIndex: 2,
    // left: "30%",
    // right: '50%',
    top: "90%",
  },
  detail_view: {
    marginTop: 35,
    marginBottom: 5,
    // flexGrow: 1,
  },
  title_rate: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  title: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  rate: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  address: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginVertical: 10,
  },
  details_icons: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  beds: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  baths: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  area: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  description: {
    flexGrow: 1,
  },
  img_container: {
    flexGrow: 1,
    marginVertical: 10,
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  reserve_view: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    flexGrow: 1,
  },
  price: {
    flex: 1,
  },
  book_now: {
    flex: 1,
    backgroundColor: "black",
    borderRadius: 10,
    paddingVertical: 15,
    paddingBottom: 16,
  },
});
